clear
import excel "/Users/stirkwang/Desktop/thesis/2013_mb_dataset_Auckland_Region/2013-mb-dataset-Auckland-Region-dwelling.xlsx", sheet("Proportions") firstrow
rename OccupiedPrivateDwellingType dtsh
rename E dt2p
rename F dtot
rename G dtnf
rename H dttt
rename DwellingRecordTypeforOccupied rtpv
rename J rtnp
rename K rttt
rename NumberofRoomsforOccupiedPriv rm1
rename M rm2
rename N rm3
rename O rm4
rename P rm5
rename Q rm6
rename R rm7
rename S rm8p
rename T rmts
rename U rmnf
rename V rmtt
rename NumberofBedroomsforOccupiedP br1
rename X br2
rename Y br3
rename Z br4
rename AA br5
rename AB br6
rename AC br7
rename AD br8p
rename AE brts
rename AF brnf
rename AG brtt
rename AH brmn
rename SuburbSizeTotaloccupieddwel sstt
save "/Users/stirkwang/Desktop/thesis/dwellingData.dta", replace
