clear
import excel "/Users/stirkwang/Desktop/thesis/2013_mb_dataset_Auckland_Region/2013-mb-dataset-Auckland-Region-individual-part-2.xlsx", sheet("Proportions") firstrow
rename ReligiousaffiliationURPNoR inrlnr
rename ReligiousaffiliationURPBudd inrlbh
rename ReligiousaffiliationURPChri inrlch
rename ReligiousaffiliationURPHind inrlhi
rename ReligiousaffiliationURPIsla inrlis
rename ReligiousaffiliationURPJuda inrlju
rename ReligiousaffiliationURPMor inrlmc
rename ReligiousaffiliationURPSpir inrlnw
rename ReligiousaffiliationURPOthe inrlor
rename ReligiousaffiliationURPObje inrlob
rename ReligiousaffiliationURPTota inrlts
rename ReligiousaffiliationURPNot inrlnf
rename P inrltt
rename CigarettesmokingbehaviourURP incbreg
rename incbreg insbreg
rename R insbex
rename S insbnv
rename T insbts
rename U insbnf
rename V insbtt
rename Legallyregisteredrelationships inrsmar
rename X inrssep
rename Y inrsnv
rename Z inrsts
rename AA inrsnf
rename AB inrstt
rename Partnershipstatusincurrentrel inptpt
rename AD inptnp
rename AE inptts
rename AF inptnf
rename AG inpttt
rename TenureholderURPOwnorPartl intnown
rename TenureholderURPDoNotOwnU intndno
rename TenureholderURPTotalpeople intnts
rename TenureholderURPNotElsewher intnnf
rename AL intntt
rename NumberofchildrenbornaliveFU inchlno
rename AN inchl
rename inchlno inchl0
rename inchl inchl1
rename AO inchl2
rename AP inchl3
rename AQ inchl4
rename AR inchl5
rename AS inchl6
rename AT inchlob
rename AU inchlts
rename AV inchlnf
rename AW inchltt
rename HighestqualificationURPNoQ ined0
rename HighestqualificationURPLeve ined1
rename AZ ined2
rename BA ined3
rename BB ined4
rename BC ineddip
rename HighestqualificationURPBach inedbclr
rename HighestqualificationURPPost inedhons
rename HighestqualificationURPMast inedmast
rename HighestqualificationURPDoct inedphd
rename HighestqualificationURPOver inedosss
rename HighestqualificationURPTota inedts
rename HighestqualificationURPNot inednf
rename BK inedtt
rename StudyparticipationURPFullt inedpft
rename StudyparticipationURPPartt inedppt
rename BN inedpftpt
rename StudyparticipationURPNotSt inedpns
rename StudyparticipationURPTotal inedpts
rename StudyparticipationURPNotst inedpnf
rename BR inedptt
rename TotalpersonalincomeURP5 ininc5000l
rename BT ininc
rename ininc5000l ininc5l
rename ininc ininc5t10
rename TotalpersonalincomeURP10 ininc10t20
rename TotalpersonalincomeURP20 ininc20t30
rename TotalpersonalincomeURP30 ininc30t50
rename TotalpersonalincomeURP50 ininc50p
rename TotalpersonalincomeURPTot inincts
rename TotalpersonalincomeURPNot inincnf
rename CA ininctt
rename TotalpersonalincomeURPMed inincmed
rename SourcesofpersonalincomeURP insi
rename insi insiws
rename CD inincse
rename inincse insise
rename CE insiid
rename CF insiac
rename CG insisu
rename CH insipe
rename CI insiub
rename CJ insisb
rename CK insidpb
rename CL ib
rename CM sa
rename CN insiob
rename CO ot
rename CP insini
rename ib insiib
rename sa insisa
rename ot insiot
rename CQ insits
rename CR insinf
rename CS insitt
save "/Users/stirkwang/Desktop/thesis/individual2Data.dta", replace

