clear
import excel "/Users/stirkwang/Desktop/thesis/2013_mb_dataset_Auckland_Region/2013-mb-dataset-Auckland-Region-individual-part-3a.xlsx", sheet("Proportions") firstrow
rename WorkandlabourforcestatusURP inlfft
rename E inlfpt
rename F inlfue
rename G inlfnp
rename H inlftt
rename inlftt inlfts
rename I inlfnf
rename J inlftt
rename StatusinemploymentEURPPaid insiepe
rename StatusinemploymentEURPEmpl insieem
rename StatusinemploymentEURPSelf insiese
rename StatusinemploymentEURPUnpa insieup
rename StatusinemploymentEURPTota insiets
rename StatusinemploymentEURPNot insienf
rename Q insiett
rename OccupationNZSCO99majorgroup inoccla
rename S inoccpr
rename T inoccta
rename U inoccc
rename V inoccss
rename W inoccaf
rename X inocctw
rename Y inoccpmo
rename Z inoccel
rename AA inocctt
rename IndustryANZSIC96divisionEUR inindaf
rename AC inindmi
rename AD inindman
rename AE inindut
rename AF inindct
rename AG wt
rename wt inindwt
rename AH inindrt
rename AI inindhp
rename AJ inindts
rename inindts inindtr
rename AK inindcom
rename AL inindfin
rename AM inindprp
rename AN inindgv
rename AO ininded
rename AP inindhlt
rename AQ inindrec
rename AR inindot
rename AS inindts
rename AT inindnf
rename AU inindtt
save "/Users/stirkwang/Desktop/thesis/individual3aData.dta", replace
